### ISSUE TITLE
(Docker ESPHome 2024.4.1) Error Pin 14 is used in multiple places

### ISSUE THREAD

**Issue by Termitebug** [techdregs/Home-Assitant-Voice-Remote#4]
` Pin 14 is used in multiple places.
  platform: gpio
  pin: 
    number: 14`

```
`deep_sleep: [source /config/va-remote.yaml:181]
  
  Pin 14 is used in multiple places.
  id: deep_sleep_1
  sleep_duration: 1h
  esp32_ext1_wakeup: 
    mode: ANY_HIGH
    pins: 
      - number: 14`
```

How do you workaround the code validator?
